### ISSUE TITLE
Rotation around defined vector 

### ISSUE THREAD

**Issue by tahereh-aram** [smparker/orient-molecule#4]
Hi,

thanks, for uploading the useful code.

I am trying to use the code and rotate a molecule around a defined vector. According to the manual, this should be done as:
python orient.py geom.xyz  -rv <angle> <x> <y> <z> 

It is not clear, however, how the values related to angle and x,y,z should be used, e.g.

python orient.py geom.xyz  -rv 30 0 0 1
python orient.py geom.xyz  -rv 30 [0 0 1]
python orient.py geom.xyz  -rv 30 [0, 0, 1]
python orient.py geom.xyz  -rv [30 0 0 1]
, ....

I have tried many versions and none of them is working. Can you please specify the correct notation?

Many thanks

**Comment by smparker** [comment]
Thanks for notifying me about the problem. I'm glad you're finding this useful so far.

There was a bug in the code for rotations around a specified vector that I just fixed. If you pull the most recent version, it should work now. The right way to call it is

```bash
python orient.py geom.xyz -rv 30 0 0 1
```

I will go ahead and close this issue but just comment on it again if for some reason it doesn't solve your issue.
