### ISSUE TITLE
Doubt about option

### ISSUE THREAD

**Issue by rafaelpap** [smparker/orient-molecule#6]
Dear Sir,
I am not sure how to use the following capability shown in the readme.

- translations

    - by any specified vector

Could you show an example?
Thanks in advance,
Rafael RP

**Comment by smparker** [comment]
Just specify the components of the translation separately.
```
orient.py -tx 1 -ty 2 -tz 3 mol.xyz > translated_mol.xyz
```
will translate the molecule by the vector (1, 2, 3)

**Comment by rafaelpap** [comment]
I see. I was looking for something like 

orient.py -vector (x,y,z) distance mol.xyz

where x,y,z are the components of the vector from the origin and distance the amount translated following the defined direction.

Thanks for the clarification.
